-- Code-review remediations (CODE_REVIEW_FULL.md §2 C5, C6 / §3 H4, H5 / §4 M4, M10).
--
-- Purely additive. Run after every prior migration. Safe to re-apply (IF NOT
-- EXISTS / DROP POLICY IF EXISTS / ALTER…ADD COLUMN IF NOT EXISTS guards).
--
-- Scope:
--   • C6  Enable RLS + read policy + UNIQUE on risk_control_mappings.
--   • C5  Preserve audit_log on organisation delete (CASCADE → SET NULL).
--   • H4  Restrict org_audit_trail INSERT to org admins + performed_by self.
--   • H5  Sanitise the audit_log payload trigger so secrets never land in logs.
--   • M4  Ensure the is_org_member()/is_org_admin() helpers exist for early
--         migrations that reference them.
--   • M10 Tighten cypher_assessment_transcripts INSERT to require session
--         ownership.

-- ─────────────────────────────────────────────
-- 0. Helper functions (idempotent — recreate)
-- ─────────────────────────────────────────────
-- These are defined in the Agent 6 multiuser migration but several earlier
-- migrations reference them. Re-declaring with CREATE OR REPLACE removes the
-- run-order dependency flagged in CODE_REVIEW_FULL.md M4.

CREATE OR REPLACE FUNCTION public.is_org_member(target_org UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE id = auth.uid()
      AND org_id = target_org
      AND status = 'active'
  )
  OR EXISTS (
    SELECT 1
    FROM public.organizations
    WHERE id = target_org
      AND owner_user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.is_org_admin(target_org UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE id = auth.uid()
      AND org_id = target_org
      AND role = 'admin'
      AND status = 'active'
  )
  OR EXISTS (
    SELECT 1
    FROM public.organizations
    WHERE id = target_org
      AND owner_user_id = auth.uid()
  );
$$;

-- ─────────────────────────────────────────────
-- C6  risk_control_mappings — RLS + UNIQUE
-- ─────────────────────────────────────────────
ALTER TABLE public.risk_control_mappings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read risk mappings" ON public.risk_control_mappings;
CREATE POLICY "Authenticated read risk mappings"
  ON public.risk_control_mappings
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- COMMENT clarifies intent — this is reference data, public to all signed-in
-- users.
COMMENT ON TABLE public.risk_control_mappings IS
  'Reference data: risk-to-control mappings per framework. Read-only to all authenticated users; writes via service role only.';

-- Stop duplicates on the natural key.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'risk_control_mappings_natural_uq'
  ) THEN
    ALTER TABLE public.risk_control_mappings
      ADD CONSTRAINT risk_control_mappings_natural_uq
      UNIQUE (risk_id, control_id, framework_id);
  END IF;
END $$;

-- ─────────────────────────────────────────────
-- C5  audit_log — preserve trail when org is deleted
-- ─────────────────────────────────────────────
-- Drop the existing FK and recreate with ON DELETE SET NULL so audit records
-- outlive the organisations they describe. Constraint name is generated by
-- PostgreSQL; query pg_constraint to find it dynamically.

DO $$
DECLARE
  conname_to_drop TEXT;
BEGIN
  SELECT conname INTO conname_to_drop
  FROM pg_constraint
  WHERE conrelid = 'public.audit_log'::regclass
    AND contype = 'f'
    AND pg_get_constraintdef(oid) ILIKE '%REFERENCES%organizations%';

  IF conname_to_drop IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.audit_log DROP CONSTRAINT IF EXISTS %I',
      conname_to_drop
    );
  END IF;
END $$;

ALTER TABLE public.audit_log
  ADD CONSTRAINT audit_log_organization_id_fkey
  FOREIGN KEY (organization_id)
  REFERENCES public.organizations(id)
  ON DELETE SET NULL;

-- Same for session_metadata_log — same compliance reasoning.
DO $$
DECLARE
  conname_to_drop TEXT;
BEGIN
  SELECT conname INTO conname_to_drop
  FROM pg_constraint
  WHERE conrelid = 'public.session_metadata_log'::regclass
    AND contype = 'f'
    AND pg_get_constraintdef(oid) ILIKE '%REFERENCES%organizations%';

  IF conname_to_drop IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.session_metadata_log DROP CONSTRAINT IF EXISTS %I',
      conname_to_drop
    );
  END IF;
END $$;

ALTER TABLE public.session_metadata_log
  ADD CONSTRAINT session_metadata_log_organization_id_fkey
  FOREIGN KEY (organization_id)
  REFERENCES public.organizations(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────
-- H5  audit_log payload sanitisation
-- ─────────────────────────────────────────────
-- Strip well-known secret column names from the JSONB payload before storage,
-- so a row containing a password/token never lands in audit_log.changed_data.

CREATE OR REPLACE FUNCTION public.sanitize_audit_payload(payload JSONB)
RETURNS JSONB
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT payload
    - 'password'
    - 'password_hash'
    - 'access_token'
    - 'refresh_token'
    - 'api_key'
    - 'anthropic_api_key'
    - 'orchestration_secret'
    - 'service_key'
    - 'stripe_secret_key'
    - 'stripe_webhook_secret'
    - 'resend_api_key'
    - 'session_token'
    - 'authorization'
    - 'cookie'
$$;

-- The existing write_audit_log() trigger (20250320000001) uses to_jsonb(NEW)
-- directly. Wrap that output via the sanitiser. We use CREATE OR REPLACE so
-- subsequent runs of the original migration win't re-introduce the unsafe
-- version (Supabase typically runs migrations in order and only once, so this
-- is a belt-and-braces).

CREATE OR REPLACE FUNCTION public.write_audit_log()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  payload JSONB;
BEGIN
  IF TG_OP = 'DELETE' THEN
    payload := public.sanitize_audit_payload(to_jsonb(OLD));
  ELSE
    payload := public.sanitize_audit_payload(to_jsonb(NEW));
  END IF;

  INSERT INTO public.audit_log (
    table_name,
    record_id,
    action,
    user_id,
    organization_id,
    changed_data
  )
  VALUES (
    TG_TABLE_NAME,
    COALESCE((NEW.id)::TEXT, (OLD.id)::TEXT),
    TG_OP,
    auth.uid(),
    CASE
      WHEN TG_TABLE_NAME = 'organizations' THEN COALESCE(NEW.id, OLD.id)
      ELSE COALESCE(
        (payload->>'organization_id')::UUID,
        (payload->>'org_id')::UUID
      )
    END,
    payload
  );

  RETURN COALESCE(NEW, OLD);
END;
$$;

-- ─────────────────────────────────────────────
-- H4  org_audit_trail — INSERT only by org admins, only as self
-- ─────────────────────────────────────────────

DROP POLICY IF EXISTS "Members insert org audit trail" ON public.org_audit_trail;
DROP POLICY IF EXISTS "Org members insert" ON public.org_audit_trail;
DROP POLICY IF EXISTS "Admins insert org audit trail" ON public.org_audit_trail;

CREATE POLICY "Admins insert org audit trail"
  ON public.org_audit_trail
  FOR INSERT
  WITH CHECK (
    public.is_org_admin(org_id)
    AND performed_by = auth.uid()
  );

-- ─────────────────────────────────────────────
-- M10  cypher_assessment_transcripts — require session ownership on INSERT
-- ─────────────────────────────────────────────

DROP POLICY IF EXISTS "Cypher transcripts user-only insert" ON public.cypher_assessment_transcripts;

CREATE POLICY "Cypher transcripts user-only insert"
  ON public.cypher_assessment_transcripts
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.assessment_sessions s
      WHERE s.id = session_id
        AND s.user_id = auth.uid()
    )
  );

-- ─────────────────────────────────────────────
-- Helpful FK indexes that were missing (CODE_REVIEW_FULL.md M6)
-- ─────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_team_responses_user
  ON public.team_responses(user_id);

CREATE INDEX IF NOT EXISTS idx_domain_assignments_assigned_by
  ON public.domain_assignments(assigned_by);

CREATE INDEX IF NOT EXISTS idx_final_answers_admin
  ON public.final_answers(admin_id);
